export const fakeSmallMenu = [ // pour tests
  {
    id: 1,
    imageSource: "/images/cupcake-item.png",
    title: "ChocoBliss",
    price: 9.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/cupcake-item.png",
    title: "SweetZing",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
]

export const fakeMenu = [
  {
    id: 1,
    imageSource: "/images/cupcake-item.png",
    title: "BerryJoy",
    price: 3.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/cupcake-item.png",
    title: "MintCharm",
    price: 5.4985,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: "/images/cupcake-item.png",
    title: "FrostGlo",
    price: 8.367,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: "/images/cupcake-item.png",
    title: "LushCup",
    price: 6.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: "/images/cupcake-item.png",
    title: "VelvetCup",
    price: 5.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    imageSource: "/images/cupcake-item.png",
    title: "ZestyFun",
    price: 7.156,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    imageSource: "/images/cupcake-item.png",
    title: "BlissZu",
    price: 7.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 8,
    imageSource: "/images/cupcake-item.png",
    title: "ZingCup",
    price: 6.6,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 9,
    imageSource: "/images/cupcake-item.png",
    title: "FrostJoy",
    price: 5.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 10,
    imageSource: "/images/cupcake-item.png",
    title: "CocoZest",
    price: 4.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
]
